/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task10_dev;

import org.hibernate.Session;
import task10_dev.CRUDService.ClientCrudService;
import task10_dev.CRUDService.PlanetCrudService;
import task10_dev.DataBase.DataBase;
import task10_dev.DbServises.DatabaseInitService;
import task10_dev.Entity.Client;
import task10_dev.Entity.Planet;
import task10_dev.hibernate.HibernateUtil;

import java.util.List;

public class App {


    public static void main(String[] args) {

        HibernateUtil util = HibernateUtil.getINSTANCE();

        Session session = util.getSessionFactory().openSession();


    }
}
